# Generated by Django 5.2.3 on 2025-06-21 18:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_consume'),
    ]

    operations = [
        migrations.AddField(
            model_name='consume',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='food',
            name='calories',
            field=models.IntegerField(help_text='in kcal'),
        ),
        migrations.AlterField(
            model_name='food',
            name='carbs',
            field=models.FloatField(help_text='in grams'),
        ),
        migrations.AlterField(
            model_name='food',
            name='fats',
            field=models.FloatField(help_text='in grams'),
        ),
        migrations.AlterField(
            model_name='food',
            name='protein',
            field=models.FloatField(help_text='in grams'),
        ),
    ]
